version: "3.3"

services:
  flask:
    restart: unless-stopped
    build: .
    image: roku_sleep
    container_name: roku_sleep
    network_mode: "host"
    environment:
      - FLASK_PORT=${FLASK_PORT}